### ISSUE TITLE
Add who picked indicator

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/NetDraftJ#3]
Just to show everyone who hasn't picked yet, not really necessary

**Comment by hellosamblack** [comment]
You had mentioned that it could lead to ganging up on slow pickers, which is true.  Maybe just debug output on the server side?  "[Name] has picked [Redacted]".  Last time when someone had the wrong version and could only pick "null" it ended up being all of us counting cards and verbally comparing just to see if the server had somehow not registered one of our picks.

**Comment by AEFeinstein** [comment]
Yeah, I can post server debug whenever a player picks a card easily enough. I really should just post redacted debug whenever any message is received.
